vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        User:
            upload_destination: '%kernel.project_dir%/assets/uploads/images'
            uri_prefix: '/uploads/photos'
            delete_on_remove: true
            delete_on_update: true
            inject_on_load: false